### Set Streamlit Secrets:
                ```toml
                # .streamlit/secrets.toml
                [SUPABASE]
                url = "ysfkukxlvmcbndfdltkv"
                key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZmt1a3hsdm1jYm5kZmRsdGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0MDQ4MTEsImV4cCI6MjA4Mjk4MDgxMX0.EWspuoDIynOzeAlBqqtUGwpqhbmMFF4nmPHkpy2n2hg"
                ```
